---
title: "Publications"
output: 
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Please find my Google Scholar profile [here](https://scholar.google.com/citations?user=TXO-bJcAAAAJ&hl=en&oi=ao)

A pdf copy of my CV is available  [here](amypitts_cv_oct2023.pdf). 


--- 

### Peer Reviewed Publications

- **Pitts, A.J.** & Fowler, C.R. (2024). Comparison of open-source software for
producing directed acyclic graphs. *Journal of Causal Inference*. vol. 12, no. 1, 2024, pp. 20230031. [https://doi.org/10.1515/jci-2023-0031](https://doi.org/10.1515/jci-2023-0031)
- Singh, T., **Pitts, A.J.**, Miles, C.H., Ing, C.H. (2023). Anesthetic Exposure During
Early Childhood and Neurodevelopmental Outcomes: Our Current Understanding.
*Current Anesthesiology Reports* [https://doi.org/10.1007/s40140-023-00592-y](https://doi.org/10.1007/s40140-023-00592-y)
- Lawlor, M.K., Ng, V., Ahmed, S., Dershowitz, L., Brener, M.I., Kampaktsis, P., **Pitts, A.,**
Vahl, T., Nazif, T., Leon, M. and George, I. (2023). Baseline characteristics and clinical
outcomes of a tricuspid regurgitation referral population. *The American Journal of Cardiology*, 196, (pp.22-30).
- Lawlor, M., Ng, V.G., Ahmed, S., Dershowitz, L., Brener, M., Kampaktsis, P., **Pitts, A.,**
Vahl III, T.P., Nazif, T., Leon, M.B. and George, I., 2023. Right Atrial Pressure in
Pulmonary Hypertension Assessment in Tricuspid Regurgitation. *Journal of the American College of Cardiology*, 81(8_Supplement), pp.1970-1970.
- **Pitts, A.,** & Rivas, P., "Finding Time Series Breakpoints with Fully Connected Neural Networks", *Int'l Conf. Artificial Intelligence CSREA Press.* 2019. p.352-357. [ISBN: 1-60132-501-0](https://csce.ucmss.com/cr/books/2019/LFS/CSREA2019/ICA4059.pdf).

###  Select Works in Progress

- Duong, N.Q., **Pitts, A.J.,** Kim, S. \& Miles, C.H. Sensitivity analysis for transportability in multi-study, multi-outcome settings [arXiv preprint arXiv:2301.02904](https://arxiv.org/pdf/2301.02904.pdf) (2023).
- **Pitts, A.J.**, Yomogida, M., Aidala, A., Gelman, A., Chen, Q. Inference of health outcomes
among patients with HIV during COVID-19 pandemic: using MRP model to improve
survey representativeness. *(in preparation)*

---

### Other Projects

##### Association of Bayesian Go/No-Go Design in Early Oncology Studies
This is a project completed during my internship at Bristol Myers Squibb. It is a 
[shiny app](https://amypitts.shinyapps.io/go_nogo_early_oncology_studies/) that explores how the Simon's Two-Phase Design can be adapted to a dual criterion Bayesian design.

##### Dose Escalation Methods
This is the second project that I completed during my time at Bristol Myers Squibb. I developed a 
[shiny app](https://amypitts.shinyapps.io/dose_escalation_app/) that compares 11 different dose escalation methods through user specified simulations. It also compares decision tables for the methods that can be summarized into one. 

##### Missing Data in Cancer Studies. 
View an interactive visualization of how missing data introduce bias in my [Shiny App](https://amypitts.shinyapps.io/Missing_Data/)! 

---
