---
title: "Academic"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is home to all my academic accomplishments. A pdf copy of my CV is available  [here](AmyPitts_cv.pdf). Please reach out if you have any questions. 

--- 

## Education 

#### Columbia University, Mailman School of Public Health 

* **Location**: New York, NY  
* **Expected Graduation**: Spring 2025
* **Degree**: Doctorate of Philosophy  
* **Area of Study**: Biostatistics



#### Marist College, 

* **Location**: Poughkeepsie, NY 
* **Graduation**: May 2020  Honors: Summa Cum Laude, Honors in Mathematics 
* **Degree**: Bachelor of Science 
* **Double Major**: Applied Mathematics and Data Science & Analytics 
* **Minor**: Computer Science 


--- 

## Interesting Projects
Welcome to my portfolio showcasing a curated collection of projects that I've accomplished during my academic journey.

##### Association of Bayesian Go/No-Go Design in Early Oncology Studies
This is a project completed during my internship at Bristol Myers Squibb. It is a 
[shiny app](https://amypitts.shinyapps.io/go_nogo_early_oncology_studies/) that explores how the Simon's Two-Phase Design can be adapted to a dual criterion Bayesian design.

##### Dose Escalation Methods
This is the second project that I completed during my time at Bristol Myers Squibb. I developed a 
[shiny app](https://amypitts.shinyapps.io/dose_escalation_app/) that compares 11 different dose escalation methods through user specified simulations. It also compares decision tables for the methods that can be summarized into one. 

##### Missing Data in Cancer Studies. 
View an interactive visualization of how missing data introduce bias in my [Shiny App](https://amypitts.shinyapps.io/Missing_Data/)! 

##### Finding Time Series Breakpoints with Fully Connected Neural Networks
Here is the published [paper](https://csce.ucmss.com/cr/books/2019/LFS/CSREA2019/ICA4059.pdf)!

---

## Experience 

#### Research Analyst (2021-Present)
Location: Biostatistics Department, Mailman School of Public Health

- Assists in the development of methods and sensitivity analysis for transportability in multi-study, multi-outcome settings and their applications to cognitive remediation therapy for patients with schizophrenia, Mentor: Dr. Caleb H. Miles
- Develops methods for graphical causal models and identification of direct effects with positivity violations and their applications to the causal effect of anesthesia on fetal development, Mentor: Dr. Caleb H. Miles
- Implements MRP models to improve survey representativeness and the inference of health outcomes among patients with HIV during COVID-19 pandemic, Mentor: Dr. Qixuan Chen
- Creates reproducible reports and visualizations to share with collaborators using tidyverse, R Markdown, and RShiny
- Attends multidisciplinary meetings to discuss both methods and applications

#### Graduate Teaching Assistant (2020-Present)
Location: Biostatistics Department, Mailman School of Public Health

- Fosters learning through holding weekly office hour, and answering student questions during class and over email 
- Provides detailed feedback on weekly assignments, quizzes and projects  
- Classes include Introduction to Data Science in R, Randomized Clinical Trials, Biostatistical Methods II,  Statistical Methods for Casual Inference, and Data Science II

#### Biostatistics Research Fellow  (Summer 2021)
Location: Bristol Myers Squibb, Remote Internship 

- Selected to be a part of the 2021 summer Bristol Myers Squibb Internship Program in the Biostatistics department.
- Explored two projects, one comparing dose escalation designs through simulations and another looking at go/no go decision. Both project shiny apps are found above. 

#### Math Lab Lead Tutor (2018-2020) 
Location:Department of Mathematics, Marist College

- Supervise, train, and administrate staff of six students
- Provide tutoring in the Math Lab, a peer help/tutoring center staffed entirely by students 
- Courses covered are: Calculus with Management Application, Calculus I-III, Linear Algebra, Differential Equations, Introduction to Mathematical Reasoning, Mathematical Analysis 


#### Biostatistics Research Fellow (Summer 2019) 
Location: Memorial Sloan Kettering Cancer Center, New York, NY

- Accepted to competitive Quantitative Sciences Undergraduate Research Experience (QSURE)  
- Explored the effects of missing data in cancer studies under advisement of attending biostatistician
- Created a RShiny Application currently accessible online. Paper currently in process of being written
- Abstract accepted for both a presentation and poster session at the Joint Mathematics Meetings in January 2020 


#### Research Experience for Undergraduates (REU) (Summer 2018) 
Location: Lafayette College, Easton, Pennsylvania 

- Developed a Bayesian procedure to detect breakpoints in time series alongside two other undergrad students and a professor
- Produced working R code and a rough draft of a paper that is in the process of being edited to eventually be submitted for publication 

---

## Relevant Skills 

**Programming Languages:**  R, RStudio, LaTeX, git, GitHub, PASS, Python, HTML, CSS, JavaScript, SQL, MATLAB, Java 

**Statistical Skills:** Causal Inference, Hypothesis testing, Regression Techniques (linear, glm, lasso, ridge), Multivariate, Longitudinal and Survival Analysis, Neural Networks/Deep Learning, Bayesian Approaches,  Stochastic Processes 

**Data Visualization Tools:** RShiny, ggplot, gtsummary, Rmarkdown, tikZ, D3, tableau

--- 

## Relevant Course Work

#### Columbia University (PhD)
- P9186: Statistical Practices and Research for Interdisciplinary Sciences II (SPRIS II)
- P9185: Statistical Practices and Research for Interdisciplinary Sciences I (SPRIS I)
- P9130: Advanced Methods
- P9120: Data Mining 
- P9111: Asymptotic Statistics 
- P9110: Theory of Statistical Inference II
- P9109: Theory of Statistical Inference
- P9104: Probability for Biostatisticians 
- P8160: Advanced Statistical Computing 
- P8140: Randomized Clinical Trials
- P8131: Biostatisic Methods II
- P8130: Biostatisic Methods I
- P8124: Graphical Models for Complex Health Data
- P8122: Statistical Methods for Causal Inference 
- P8109: Statistical Inference 
- P8106: Data Science II
- P8105: Data Science I
- P8104: Probability
- P6400: Priciples of Epidemiology 

#### Marist College (B.S.)
Double Major in Applied Mathematics and Data Science with a Minor in Computer Science

**Mathematics**: Applied Statistics, Differential Equations, Applied Mathematics, Complex Analysis, Mathematical Analysis, Numerical Analysis, Operations Research, Abstract Algebra, Independent Study in Math Biology, Computational Linear Algebra, Probability and Statistics

**Computer Science**: Algorithms, Software Development I-II, Database Management

**Data Science**: Machine Learning, Data Mining, Data Analysis, Data Visualization, Data Management
courses 

---

## Publications/ Presentations / Posters 

#### Publications

- **Pitts, Amy,** & Rivas, Pablo, "Finding Time Series Breakpoints with Fully Connected Neural Networks", *Int'l Conf. Artificial Intelligence CSREA Press.* 2019. p.352-357. [ISBN: 1-60132-501-0](https://csce.ucmss.com/cr/books/2019/LFS/CSREA2019/ICA4059.pdf).
- Duong, Ngoc Q., **Pitts, Amy J.,** Kim, Soohyun \& Miles, Caleb H. ``Sensitivity analysis for transportability in multi-study, multi-outcome settings'' [arXiv preprint arXiv:2301.02904](https://arxiv.org/pdf/2301.02904.pdf) (2023).
- **Pitts, Amy J.** \& Fowler, Charlotte. ``Comparison of open-source software for plotting directed acyclic graphs" in preparation. 
- **Pitts, Amy,** & Patil, Sujata. "Missing data in cancer studies" in preparation.

#### Presentations
- Pitts, Amy. ``Inference of health outcomes among patients with HIV during covid-19 pandemic: using mrp model to improve survey representativeness", American Association for Public Opinion Research (AAPOR). Philadelphia, PA. May 2023.
- Pitts, Amy. Fowler, Charlotte. ["Software to Draw DAGs"](http://cu-biostats-computing-club.org/resources_files/DAG_pres.html#(1)), Causal Inference Learning Group. Feb 2023. 
- Pitts, Amy. ["R-Shiny Crash Course"](http://cu-biostats-computing-club.org/resources_files/shiny_pres/cc_pres_nov_2022.pdf) Columbia Biostatistics Computing Club. Nov 2022. 
- Pitts, Amy. "Bayesian Go/No-Go Rules & Two-stage Designs and Comparison of Dose Escalation Designs in Early Oncology Studies", Bristol Myers Squibb. Microsoft Teams. August 2021. 
- Pitts, Amy. "Predicting Mesothelioma Disease Status Using Demographic, Clinical, and Exposure-Related Factors", Marist College Pi Mu Epsilon Induction Ceremony. May 2021. 
- Pitts, Amy. Kwizera, Muhire. "Python Tutorial", Columbia Biostatistics Computing Club. December 2020.
-  Pitts, Amy. Mulligan, Kaitlyn. & Allison Nowakowski. "The Machine Learning Quote Generator" Marist College School of Computer Science & Mathematics. Cisco Webex. May 2020.
- Pitts, Amy. "SeminaR: an R tutorial looking at shiny applications" Marist College Department of Mathematics. Poughkeepsie, NY. November 2019.  
-  Pitts, Amy. "My Research Experience at Memorial Sloan Kettering Cancer Center'' Marist College Department of Mathematics. Poughkeepsie, NY. October 2019. 
- Pitts, Amy. "Overleaf Overview'' Department of Epidemiology and Biostatistics at Memorial Sloan Kettering Cancer Center. New York, NY. August 2019.
-  Pitts, Amy, & Rivas, Pablo. "Finding time series breakpoints with fully connected neural networks" 2019 International Conference of Artificial Intelligence. Las Vegas, NV. July, 2019. 
- Pitts, Amy. "Missing Data in Cancer Studies" QSURE Final Presentations hosted in the Department of Epidemiology and Biostatistics at Memorial Sloan Kettering Cancer Center. New York, NY. July 2019.
-  Pitts, Amy. Haglich, Kathryn. & Neitzel, Sarah. "A Bayesian method for locating breakpoints in time series" Joint Mathematics Meetings. Baltimore, MD. January 2019.
-  Pitts, Amy. "My Research Experience at Lafayette College" Marist College Department of Mathematics. Poughkeepsie, NY. September 2018. 

#### Poster Presentations
- Pitts, Amy. ``Inference of health outcomes among patients with HIV during covid-19 pandemic: using mrp model to improve survey representativeness", Eastern North American Region International Biometric Society (ENAR). Nashville, TN. Mar 2023.
- Pitts, Amy. Haglich, Kathryn. Neitzel, Sarah. & Leibner, Jeffery. "A Bayesian method for locating breakpoints in time series" ACM New York Celebration of Women in Computing. Lake George, NY. April 2019.
- Pitts, Amy. Haglich, Kathryn. Neitzel, Sarah. & Leibner, Jeffery. "A Bayesian method for locating breakpoints in time series" Joint Mathematics Meeting. Baltimore, MD. January 2019.


---

## Activities / Honors
#### Activities

- Board Member, Columbia University Biostatistics Computing Club, (2020-Present)
- Chair of Student Committee, Columbia Biostatistics Department Master Practicum Symposium, (2023)
- President, Marist College Alpha Pi Chapter, Pi Mu Epsilon (2019-2020) 
- President and Founder, Association for Women in Mathematics (AWM) Chapter at Marist College (2019-2020)
- Vice President, Marist Math Club (2019-2020)
- Treasurer, Equestrian Team (2017-2020)
- Member of Marist Team, 79th annual William-Lowell Putnam Mathematical Competition (2018)
   
#### Honors

- Invited to give a key note presentation and the presidential address at the Marist College Pi Mu Epsilon Induction Ceremony (2021)
- Marist College Excellence in Mathematics Award (2020)
- Inducted into the Marist College Pi Mu Epsilon Chapter Mathematics Honors Society (2019)
- Recipient of an Outstanding Poster Award at the Joint Mathematics Meeting, Baltimore (2019)
- Student Subcommittee Chair, 2019 Marist Math Department Faculty Search Committee (2019)
- Recipient of the Marist College Early Career Undergraduate Mathematics Research Award (2018)
- Awarded Best Visualization at DataFest located at Vassar College (2018)
- Winner of the Hack Harassment Category in Marist College Hackathon (2016)



